### ISSUE TITLE
Get gstreamer logging Text from gst_device_to_rtp.py

### ISSUE THREAD

**Issue by BestITUserEUW** [madams1337/python-opencv-gstreamer-examples#10]
Hey, 
i have a question do you know a way to get the Output of the gstreamer logging from the cv2.VideoWriter class.
I want to wait till gstreamer Stream is Ready and then execute the Python Code that writes to gstreamer pipeline and also process Errors on gstreamer side if they appear.

**Comment by mad4ms** [comment]
Hey,
sorry for the late answer.

There is a way:

As stated in the [gst-doc](https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c), the environment variable `GST_DEBUG` controls the level of debug.

I found the command `export GST_DEBUG=4` as the most valuable, because it also prints warnings that may cause malfunctions in the gstreamer pipe. Put that command before you execute your scripts and a lot of (usable and unusable) output should appear.

Best
