### ISSUE TITLE
How to use Gstreamer to create rtsp server to enable multiple clients to access 

### ISSUE THREAD

**Issue by scy-ai** [madams1337/python-opencv-gstreamer-examples#2]
I used your example. They work well, but the rtsp server can only output one rtsp stream. How to make the server output multiple streams for client access?

**Comment by mad4ms** [comment]
Usually you don't output multiple streams but rather one to a multicast address as shown in the stream_multicast.sdp - file.

I'm trying to look up how to stream the RTSP to such an address.
Since my time is currently quite limited due to work, you can also try to translate this example: [Example 1](https://github.com/GStreamer/gst-rtsp-server/blob/master/examples/test-multicast.c) and maybe this as well [Example 2](https://github.com/GStreamer/gst-rtsp-server/blob/master/examples/test-multicast2.c)

**Comment by scy-ai** [comment]
> 通常，您不会输出多个流，而是将一个流输出到多播地址，如 stream_multicast.sdp 文件中所示。
> 
> 我正在尝试查找如何将 RTSP 流式传输到这样的地址。
> 由于我目前由于工作的关系非常有限，你也可以尝试翻译这个例子：[示例1](https://github.com/GStreamer/gst-rtsp-server/blob/master/examples/test-multicast.c)，也许这也是[示例2](https://github.com/GStreamer/gst-rtsp-server/blob/master/examples/test-multicast2.c)

**Comment by scy-ai** [comment]
Thanks for your reply, I will try it according to your guidance. All the best with your work.
