### ISSUE TITLE
Implementing Gstreamer command in OpenCV

### ISSUE THREAD

**Issue by seabass1217** [madams1337/python-opencv-gstreamer-examples#5]
Hi,

I'm new to Gstreamer and OpenCV and I'm having problems with implementing gstreamer commands in OpenCV.  The below command works fine on the command-line but I cannot figure out how to implement in OpenCV.

Gstreamer command: 

`st-launch-1.0 rtspsrc location=rtsp://192.168.0.79:8080/h264_ulaw.sdp protocols=udp latency=50 drop-on-latency=true ! queue ! rtph264depay ! h264parse ! nvv4l2decoder enable-frame-type-reporting=1 ! queue ! omxh264enc bitrate=4000000 ! video/x-h264 ! rtspclientsink location=rtsp://localhost:8554/mystream`

My OpenCV Code:

`cap = cv2.VideoCapture(" rtspsrc rtsp://192.168.0.79:8080/h264_ulaw.sdp ! appsink ")
#gst_str = "appsrc ! videoconvert ! omxh264enc ! rtph264pay ! rtspclientsink location=rtsp://localhost:8554/mystream"
#out = cv2.VideoWriter(gst_str, 0, 30, (640, 480), True)`

Any help is greatly appreciated.

**Comment by mad4ms** [comment]
Hi,

i don't have much experience working with the `rtspsrc`, but i think there's more to it than just piping it to the appsink.
If you take a look at [the commands in my other repo](https://github.com/mad4ms/GStreamerOpenCVExamples/blob/master/commands.h), you can find an example on how to deal with `udpsrc` (RTP instead of RTSP):
`const std::string rtp2appsink_H264 = "udpsrc port=5000 ! application/x-rtp, media=video, clock-rate=90000, encoding-name=H264, payload=96 ! rtph264depay ! decodebin ! videoconvert ! appsink";`

Here, the incoming video data is flagged with it's properties, extracted from the rtp stream, decoded to binary, videoconverted and finally put in an appsink. Reason for that is incoming data is encoded (e.g. h264) and encapsulated (rtph264). OpenCV/appsink wants to have raw images.

Hope this helps. Best.

**Comment by seabass1217** [comment]
@mad4ms,  Thanks for the feedback!
